language: node_js
node_js:
        - 12.16.2
deploy:
        provider: elasticbeanstalk
        access_key_id:
                secure: "$ACCESSKEYID"
        secret_access_key:
                secure: "SECRETACCESSKEY"
        region: "us-east-1"
        app: "package-fiend"
        env: "Pkgfnd-env"
        bucket_name: "elasticbeanstalk-us-east-1-236301425402"
